# Generated by Django 5.1.4 on 2026-05-06 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_categories', models.JSONField(default=dict, help_text='Ex: {1: 12.5, 3: 8.0} (category_id: score)')),
                ('favorite_tags', models.JSONField(default=dict, help_text="Ex: {'bois': 7.5, 'portrait': 5.0}")),
                ('avg_price_viewed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_price_purchased', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_rebuilt_at', models.DateTimeField(blank=True, null=True)),
                ('events_count', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil client (reco)',
            },
        ),
        migrations.CreateModel(
            name='BehaviorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'Vue produit'), ('cart', 'Ajout au panier'), ('customize', 'Personnalisation'), ('purchase', 'Achat confirmé'), ('review_pos', 'Avis positif (4-5★)'), ('review_neg', 'Avis négatif (1-2★)')], db_index=True, max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category_id', models.IntegerField(blank=True, help_text='Dénormalisé pour accélérer les requêtes agrégées', null=True)),
                ('tags_snapshot', models.CharField(blank=True, help_text="Tags du produit au moment de l'événement", max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_events', to='catalogue.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement comportemental',
                'verbose_name_plural': 'Événements comportementaux',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['user', 'event_type', 'occurred_at'], name='recommendat_user_id_04671b_idx'), models.Index(fields=['product', 'event_type'], name='recommendat_product_5d7522_idx'), models.Index(fields=['user', 'product'], name='recommendat_user_id_ad26d0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('event_type', 'view')), fields=('user', 'product', 'event_type'), name='unique_view_per_user_product_hour')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('home', "Page d'accueil"), ('product', 'Page produit (similaires personnalisés)'), ('cart', 'Page panier'), ('global', 'Recommandations globales')], max_length=20)),
                ('product_ids', models.JSONField(default=list)),
                ('scores', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('is_stale', models.BooleanField(default=False, help_text='Marqué True après un événement majeur → recalcul prioritaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_caches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cache recommandations',
                'unique_together': {('user', 'context')},
            },
        ),
    ]
