# Generated by Django 5.1.4 on 2026-05-05 02:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_name', models.CharField(help_text="Nom de l'atelier ou boutique", max_length=200)),
                ('shop_description', models.TextField(blank=True, help_text="Description courte de l'atelier (~200 mots)")),
                ('shop_banner', models.ImageField(blank=True, null=True, upload_to='artisans/banners/')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('quarter', models.CharField(blank=True, help_text="Quartier / zone de l'atelier", max_length=200)),
                ('specialties', models.CharField(blank=True, help_text='Ex: cadres bois, aquarelle, portraits', max_length=500)),
                ('payout_phone', models.CharField(blank=True, help_text='Numéro Mobile Money pour recevoir les commissions', max_length=20)),
                ('payout_operator', models.CharField(blank=True, choices=[('mtn', 'MTN MoMo'), ('orange', 'Orange Money')], max_length=10)),
                ('total_sales_count', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total des commissions prélevées par Kadoya', max_digits=12)),
                ('total_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Montant net reversé à l'artisan", max_digits=12)),
                ('is_verified', models.BooleanField(default=False, help_text="Compte artisan vérifié par l'équipe Kadoya")),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'artisan'}, on_delete=django.db.models.deletion.CASCADE, related_name='artisan_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil artisan',
                'verbose_name_plural': 'Profils artisans',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.CharField(max_length=20)),
                ('operator', models.CharField(choices=[('mtn', 'MTN MoMo'), ('orange', 'Orange Money')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('processed', 'Versée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='artisan.artisanprofile')),
            ],
            options={
                'verbose_name': 'Demande de retrait',
                'verbose_name_plural': 'Demandes de retrait',
                'ordering': ['-created_at'],
            },
        ),
    ]
