# Generated by Django 6.0.4 on 2026-05-05 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngravingFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('css_family', models.CharField(help_text='Famille CSS ou URL Google Fonts', max_length=200)),
                ('preview_text', models.CharField(default='Avec tout mon amour', help_text="Texte affiché en aperçu dans l'UI", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Police de gravure',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FrameOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='Ex: Petit (13x18 cm)', max_length=100)),
                ('width_cm', models.DecimalField(decimal_places=1, max_digits=6)),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=6)),
                ('material', models.CharField(choices=[('bois_clair', 'Bois clair'), ('bois_fonce', 'Bois foncé'), ('bois_noir', 'Bois noir'), ('metal_or', 'Métal doré'), ('metal_arg', 'Métal argenté'), ('plastique', 'Plastique moderne')], max_length=20)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, help_text='Prix additionnel par rapport au prix de base du produit', max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_options', to='catalogue.product')),
            ],
            options={
                'verbose_name': 'Option de cadre',
                'verbose_name_plural': 'Options de cadres',
                'ordering': ['order', 'width_cm'],
            },
        ),
        migrations.CreateModel(
            name='CustomizationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_photo', models.ImageField(blank=True, null=True, upload_to='customizations/photos/%Y/%m/')),
                ('uploaded_photo_thumb', models.ImageField(blank=True, help_text='Miniature générée automatiquement via Pillow', null=True, upload_to='customizations/thumbs/%Y/%m/')),
                ('engraving_text', models.CharField(blank=True, max_length=200)),
                ('engraving_position', models.CharField(choices=[('top', 'Haut'), ('bottom', 'Bas'), ('left', 'Gauche'), ('right', 'Droite')], default='bottom', max_length=20)),
                ('session_key', models.CharField(db_index=True, help_text='session.session_key Django (pour invités)', max_length=40)),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Terminée'), ('abandoned', 'Abandonnée'), ('ordered', 'Commandée')], default='in_progress', max_length=20)),
                ('current_step', models.PositiveSmallIntegerField(default=1, help_text='Étape courante du wizard (1=Upload, 2=Cadre, 3=Gravure, 4=Aperçu)')),
                ('computed_price', models.DecimalField(blank=True, decimal_places=2, help_text='Prix final = prix produit + extra_price du cadre', max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_sessions', to='catalogue.product')),
                ('user', models.ForeignKey(blank=True, help_text='Null si session invité (non connecté)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customization_sessions', to=settings.AUTH_USER_MODEL)),
                ('font', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customization.engravingfont')),
                ('frame_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customization.frameoption')),
            ],
            options={
                'verbose_name': 'Session de personnalisation',
                'verbose_name_plural': 'Sessions de personnalisation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key', 'status'], name='customizati_session_ce1aac_idx'), models.Index(fields=['user', 'status'], name='customizati_user_id_d87a60_idx')],
            },
        ),
    ]
