# Generated by Django 5.1.4 on 2026-05-06 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], help_text='Note de 1 à 5 étoiles')),
                ('title', models.CharField(blank=True, help_text="Titre court de l'avis (optionnel)", max_length=150)),
                ('body', models.TextField(help_text="Corps de l'avis (min 10 caractères)")),
                ('status', models.CharField(choices=[('pending', 'En attente de modération'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True, help_text='Motif de rejet visible par le client')),
                ('artisan_reply', models.TextField(blank=True, help_text="Réponse publique de l'artisan à cet avis")),
                ('artisan_replied_at', models.DateTimeField(blank=True, null=True)),
                ('helpful_count', models.PositiveIntegerField(default=0, help_text='Nombre de personnes ayant trouvé cet avis utile')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Commande qui justifie cet avis (doit être DELIVERED)', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, help_text='OrderItem spécifique (pour les commandes multi-articles)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalogue.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avis client',
                'verbose_name_plural': 'Avis clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Photo du produit reçu par le client', upload_to='reviews/photos/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Miniature 300×300 générée automatiquement', null=True, upload_to='reviews/thumbs/%Y/%m/')),
                ('caption', models.CharField(blank=True, help_text='Légende optionnelle', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reviews.review')),
            ],
            options={
                'verbose_name': 'Photo avis',
                'verbose_name_plural': 'Photos avis',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'status'], name='reviews_rev_product_0aaa55_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'status'], name='reviews_rev_user_id_194b3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_review_per_user_per_product'),
        ),
    ]
