# Generated by Django 5.1.4 on 2026-05-05 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flw_tx_ref', models.CharField(db_index=True, help_text='tx_ref envoyé à Flutterwave = order.reference', max_length=100, unique=True)),
                ('flw_transaction_id', models.CharField(blank=True, db_index=True, help_text='ID transaction Flutterwave (reçu dans le webhook)', max_length=100)),
                ('flw_ref', models.CharField(blank=True, help_text='Référence interne Flutterwave', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='XAF', max_length=5)),
                ('payment_method', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money')], default='mtn', max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initié'), ('pending', 'En attente confirmation client'), ('success', 'Succès'), ('failed', 'Échec'), ('timeout', 'Expiré'), ('cancelled', 'Annulé')], default='initiated', max_length=20)),
                ('flw_init_response', models.JSONField(blank=True, help_text="Réponse JSON de l'appel d'initiation", null=True)),
                ('flw_webhook_payload', models.JSONField(blank=True, help_text='Payload brut du webhook reçu', null=True)),
                ('flw_verify_response', models.JSONField(blank=True, help_text="Réponse de l'appel de vérification", null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Timestamp de confirmation paiement', null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentative de paiement',
                'verbose_name_plural': 'Tentatives de paiement',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['flw_tx_ref'], name='payments_pa_flw_tx__335dbb_idx'), models.Index(fields=['status', 'initiated_at'], name='payments_pa_status_b26a6e_idx')],
            },
        ),
    ]
