# Generated by Django 5.1.4 on 2026-05-05 13:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisan', '0001_initial'),
        ('catalogue', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_id', models.PositiveIntegerField(help_text="ID de l'avis signalé (FK vers Review — Sprint 8)")),
                ('reason', models.CharField(choices=[('spam', 'Spam / faux avis'), ('offensive', 'Contenu offensant'), ('irrelevant', 'Hors sujet'), ('fake', 'Avis falsifié'), ('other', 'Autre')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Avis conservé'), ('removed', 'Avis supprimé')], default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signalement avis',
                'verbose_name_plural': 'Signalements avis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('stock_low', '⚠️ Stock bas'), ('order_paid', '💰 Commande payée'), ('custom_order', '🎨 Commande perso à valider'), ('withdrawal', '💳 Demande de retrait'), ('artisan_signup', '👤 Nouvel artisan'), ('review_report', '🚨 Avis signalé'), ('product_submit', '📦 Produit soumis')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, help_text="URL vers laquelle pointe le bouton d'action", max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_artisan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artisan.artisanprofile')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.product')),
            ],
            options={
                'verbose_name': 'Notification interne',
                'verbose_name_plural': 'Notifications internes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', 'priority', 'created_at'], name='dashboard_i_is_read_2fc0e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Ex: FETE-MERES-2024', max_length=50, unique=True)),
                ('occasion', models.CharField(blank=True, choices=[('', 'Aucune occasion'), ('fete_meres', 'Fête des mères'), ('fete_peres', 'Fête des pères'), ('tabaski', 'Tabaski'), ('noel', 'Noël'), ('nouvel_an', 'Nouvel An'), ('saint_valentin', 'Saint-Valentin'), ('custom', 'Personnalisée')], default='', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('banner_text', models.CharField(blank=True, help_text='Texte affiché sur la bannière promotionnelle du site', max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Pourcentage (%)'), ('fixed', 'Montant fixe (FCFA)'), ('free_ship', 'Livraison gratuite')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Valeur de la réduction (% ou FCFA selon discount_type)', max_digits=8)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant minimum de commande pour appliquer le code', max_digits=10)),
                ('max_discount_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Plafond de réduction max (pour les % sur grosses commandes)', max_digits=10, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text="Nombre max d'utilisations. Vide = illimité", null=True)),
                ('max_uses_per_user', models.PositiveSmallIntegerField(default=1, help_text="Nombre max d'utilisations par client unique")),
                ('current_uses', models.PositiveIntegerField(default=0, editable=False)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Laisser vide = applicable sur tout le catalogue', to='catalogue.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code promo',
                'verbose_name_plural': 'Codes promo',
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['code', 'is_active'], name='dashboard_p_code_7380f7_idx')],
            },
        ),
    ]
